# Generated by Django 5.1.6 on 2025-03-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(default='users/default.png', upload_to='users/profile_pics/'),
        ),
    ]
