# Generated by Django 5.1.6 on 2025-02-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_audio_message_image_message_video_post_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
