# Generated by Django 5.1.6 on 2025-02-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video',
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
