# Generated by Django 5.1.6 on 2025-03-15 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_story_viewers_storyview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyview',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='chat.story'),
        ),
    ]
